spring:
  application:
    name: mail-service
  mail:
    host:
      173.194.66.108
    port:
        587
    username:
      cs544.project@gmail.com
    password:
      yvhogxzjyibjxpzh
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true

server:
  port:
    8083